### ISSUE TITLE
Incompatikble pointer type for time argument in main.c

### ISSUE THREAD

**Issue by Tzaphkiel** [ColumPaget/Crayonizer#1]
Calling $ ./configure;make 
yields the following error on an Arch linux with std base-devel packages:

``` make
main.c: In function ‘CalledAsSelf’:
main.c:605:105: warning: useless storage class specifier in empty declaration
 typedef enum {ARG_V1, ARG_V2, ARG_V3, ARG_H1, ARG_H2, ARG_H3, ARG_H4, ARG_CONFIG_HELP, ARG_PMATCH_HELP, ARG_STDIN};
                                                                                                         ^
main.c: In function ‘main’:
main.c:662:1: warning: passing argument 1 of ‘time’ from incompatible pointer type
 time(&StartTime);
 ^
In file included from libUseful-2.0/includes.h:8:0,
                 from libUseful-2.0/FileSystem.h:4,
                 from libUseful-2.0/libUseful.h:23,
                 from common.h:6,
                 from main.c:20:
/usr/include/time.h:192:15: note: expected ‘time_t *’ but argument is of type ‘int *’
 extern time_t time (time_t *__timer) __THROW;
```

**Comment by ColumPaget** [comment]
Thanks for tagging that! Looks like a bit of a weird error. I'll look into it.

Colum

**Comment by Tzaphkiel** [comment]
I do not see any activity on this issue since 2014... I do not use this at the moment and have not tried recently to re-compile it. Perhaps the issue can be closed?

**Comment by ColumPaget** [comment]
Hmm, I might have forgotten to close it, or forgotten about it altogether! It's about time I had another look at Crayonizer, I've been neglecting that one recently.

**Comment by ColumPaget** [comment]
I think I fixed this long, long ago, the code says 'time_t' now, but just serially forgot to close the issue. Closing it now, and a belated thanks for reporting it.
