### ISSUE TITLE
Wrong parameter to strtol()

### ISSUE THREAD

**Issue by jubalh** [ColumPaget/Crayonizer#3]
In https://github.com/ColumPaget/Crayonizer/blob/master/libUseful/PatternMatch.c#L302  we have:
```
val=strtol(Tempstr, *ptr, 10);
```

But strtol()'s second parameter is char **. So we pass the wrong type there. It would be &ptr, but I'm not sure whether that it is what we want logically. Could you check this?

**Comment by ColumPaget** [comment]
Good catch, it's exactly what you thought, should be & not *. Odd that I didn't get a compiler warning for that! Or maybe I did but wasn't watching close enough. Thanks again.

**Comment by ColumPaget** [comment]
New release available with the fix in.

**Comment by jubalh** [comment]
:-)
